### ISSUE TITLE
Consumo de recursos para construcción de casas

### ISSUE THREAD

**Issue by jh62** [GabrielCancro/stone_age_firebase#1]
El cómputo del costo de algunas acciones se desbalancea. A veces obtenes el mismo beneficio (o capaz tiene un beneficio marginal con respecto el uno del otro), pero uno puede llegar a costar más recursos.

### Ejemplo 1: mismo beneficio, pero uno cuesta más que el otro

![image](https://user-images.githubusercontent.com/22467336/191870276-61230726-7f26-4d6d-9849-c1808a6d7aa0.png)

### Ejemplo 2: beneficio marginal en comparación, pero por más recursos

![image](https://user-images.githubusercontent.com/22467336/191870329-e96da257-b29c-4ee1-bb3f-9252c400688e.png)

**Comment by jh62** [comment]
Lo cerré porque determinamos que no era un bug :D

**Comment by GabrielCancro** [comment]
mm.. ok, puede ser que la formula no sea del todo correcta, pero bueno, lo ajustamos mas adelante :)
