### ISSUE TITLE
Configuración de partidas

### ISSUE THREAD

**Issue by GabrielCancro** [GabrielCancro/stone_age_firebase#5]
![image](https://user-images.githubusercontent.com/28982719/192288632-ce93d9be-64bc-4483-8d91-9c042472baaa.png)

Armaría una forma mas "controlada" de crear partidas, sin tantas opciones ni tener que escribir..

Duracion en hs (4-8-12-24)

Partida ABIERTA (se pueden unir jugadores hasta la mitad del tiempo transcurrido)
Partida CERRADA (solo los jugadores listados podran jugar)

Cantidad de turnos ( partida a 30 o a 40 turnos? )

Turnos Progresivos (cada una hs se habilitan X turnos)
Todos los turnos al inicio

**Comment by jh62** [comment]
> Armaría una forma mas "controlada" de crear partidas, sin tantas opciones ni tener que escribir..
> Duracion en hs (4-8-12-24)
> Cantidad de turnos ( partida a 30 o a 40 turnos? )

En realidad esta buena la flexibilidad de ahora, que pones los parámetros y te calcula los tiempos. Podés crear el tipo de partida que tengas ganas. Lo que se puede hacer es en vez de campos para escribir, utilizar sliders donde solo tengas que arrastrar el dedo. Que opinas?

Despues el resto esta joya

**Comment by jh62** [comment]
PD: Activa windows! 🤣

**Comment by GabrielCancro** [comment]
jjaja, si, ni le doy pelota al cartelito..
Le puse options cosa que no haya que escribir, no habría problema en agregar o quitar opciones, avisa si se te ocurre que falte algo..
